/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'opportunityId' : IDL.Nat,
});
export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'linkedOpportunityIds' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const FileRecord = IDL.Record({
  'id' : IDL.Nat,
  'displayName' : IDL.Text,
  'opportunityId' : IDL.Nat,
  'fileType' : IDL.Text,
  'blobId' : IDL.Text,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : IDL.Text,
  'folder' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CalendarItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'timeLabel' : IDL.Text,
  'createdBy' : IDL.Text,
  'opportunityId' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Text,
  'dateTimestamp' : IDL.Int,
});
export const Opportunity = IDL.Record({
  'id' : IDL.Nat,
  'closeDate' : IDL.Int,
  'value' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'summary' : IDL.Text,
  'stage' : IDL.Text,
});
export const TodoItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'assignedTo' : IDL.Text,
  'createdAt' : IDL.Int,
  'stage' : IDL.Text,
  'opportunityId' : IDL.Opt(IDL.Nat),
  'priority' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserProfileDTO = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Comment], []),
  'addContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Contact],
      [],
    ),
  'addContactAndLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Contact],
      [],
    ),
  'addFileRecord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [FileRecord],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCalendarItem' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
      [CalendarItem],
      [],
    ),
  'createOpportunity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
      [Opportunity],
      [],
    ),
  'createTodoItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text], [TodoItem], []),
  'deleteCalendarItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteFileRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteOpportunity' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTodoItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContact' : IDL.Func([IDL.Nat], [IDL.Opt(Contact)], ['query']),
  'getOpportunity' : IDL.Func([IDL.Nat], [IDL.Opt(Opportunity)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkContactToOpportunity' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'listAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'listAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileDTO)], ['query']),
  'listCalendarItems' : IDL.Func([], [IDL.Vec(CalendarItem)], ['query']),
  'listComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'listContactsByOpportunity' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Contact)],
      ['query'],
    ),
  'listFileRecords' : IDL.Func([IDL.Nat], [IDL.Vec(FileRecord)], ['query']),
  'listOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
  'listTodoItems' : IDL.Func([], [IDL.Vec(TodoItem)], ['query']),
  'makeAdmin' : IDL.Func([IDL.Principal], [], []),
  'assignConfidentialRole' : IDL.Func([IDL.Principal], [], []),
  'demoteToUser' : IDL.Func([IDL.Principal], [], []),
  'removeContact' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unlinkContactFromOpportunity' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'updateContact' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(Contact)],
      [],
    ),
  'updateFileRecord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Opt(FileRecord)],
      [],
    ),
  'updateOpportunity' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
      [IDL.Opt(Opportunity)],
      [],
    ),
  'updateTodoItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
      [IDL.Opt(TodoItem)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'opportunityId' : IDL.Nat,
  });
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'linkedOpportunityIds' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FileRecord = IDL.Record({
    'id' : IDL.Nat,
    'displayName' : IDL.Text,
    'opportunityId' : IDL.Nat,
    'fileType' : IDL.Text,
    'blobId' : IDL.Text,
    'uploadedAt' : IDL.Int,
    'uploadedBy' : IDL.Text,
    'folder' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CalendarItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'timeLabel' : IDL.Text,
    'createdBy' : IDL.Text,
    'opportunityId' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Text,
    'dateTimestamp' : IDL.Int,
  });
  const Opportunity = IDL.Record({
    'id' : IDL.Nat,
    'closeDate' : IDL.Int,
    'value' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'summary' : IDL.Text,
    'stage' : IDL.Text,
  });
  const TodoItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'assignedTo' : IDL.Text,
    'createdAt' : IDL.Int,
    'stage' : IDL.Text,
    'opportunityId' : IDL.Opt(IDL.Nat),
    'priority' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserProfileDTO = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Comment], []),
    'addContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Contact],
        [],
      ),
    'addContactAndLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Contact],
        [],
      ),
    'addFileRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [FileRecord],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCalendarItem' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
        [CalendarItem],
        [],
      ),
    'createOpportunity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
        [Opportunity],
        [],
      ),
    'createTodoItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text], [TodoItem], []),
    'deleteCalendarItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteComment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteFileRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteOpportunity' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTodoItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContact' : IDL.Func([IDL.Nat], [IDL.Opt(Contact)], ['query']),
    'getOpportunity' : IDL.Func([IDL.Nat], [IDL.Opt(Opportunity)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkContactToOpportunity' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'listAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'listAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileDTO)], ['query']),
    'listCalendarItems' : IDL.Func([], [IDL.Vec(CalendarItem)], ['query']),
    'listComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'listContactsByOpportunity' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Contact)],
        ['query'],
      ),
    'listFileRecords' : IDL.Func([IDL.Nat], [IDL.Vec(FileRecord)], ['query']),
    'listOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
    'listTodoItems' : IDL.Func([], [IDL.Vec(TodoItem)], ['query']),
    'makeAdmin' : IDL.Func([IDL.Principal], [], []),
    'assignConfidentialRole' : IDL.Func([IDL.Principal], [], []),
    'demoteToUser' : IDL.Func([IDL.Principal], [], []),
  'makeAdmin' : IDL.Func([IDL.Principal], [], []),
  'assignConfidentialRole' : IDL.Func([IDL.Principal], [], []),
  'demoteToUser' : IDL.Func([IDL.Principal], [], []),
    'removeContact' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unlinkContactFromOpportunity' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateContact' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(Contact)],
        [],
      ),
    'updateFileRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Opt(FileRecord)],
        [],
      ),
    'updateOpportunity' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text],
        [IDL.Opt(Opportunity)],
        [],
      ),
    'updateTodoItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
        [IDL.Opt(TodoItem)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };