/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalendarItem {
  'id' : bigint,
  'title' : string,
  'timeLabel' : string,
  'createdBy' : string,
  'opportunityId' : [] | [bigint],
  'notes' : string,
  'dateTimestamp' : bigint,
}
export interface Comment {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'authorName' : string,
  'opportunityId' : bigint,
}
export interface Contact {
  'id' : bigint,
  'title' : string,
  'linkedOpportunityIds' : Array<bigint>,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface FileRecord {
  'id' : bigint,
  'displayName' : string,
  'opportunityId' : bigint,
  'fileType' : string,
  'blobId' : string,
  'uploadedAt' : bigint,
  'uploadedBy' : string,
  'folder' : string,
}
export interface Opportunity {
  'id' : bigint,
  'closeDate' : bigint,
  'value' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'summary' : string,
  'stage' : string,
}
export interface TodoItem {
  'id' : bigint,
  'title' : string,
  'assignedTo' : string,
  'createdAt' : bigint,
  'stage' : string,
  'opportunityId' : [] | [bigint],
  'priority' : string,
}
export interface UserProfile { 'name' : string }
export interface UserProfileDTO { 'principal' : Principal, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, string], Comment>,
  'addContact' : ActorMethod<[string, string, string, string], Contact>,
  'addContactAndLink' : ActorMethod<
    [string, string, string, string, bigint],
    Contact
  >,
  'addFileRecord' : ActorMethod<
    [bigint, string, string, string, string, string],
    FileRecord
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCalendarItem' : ActorMethod<
    [string, bigint, string, string, [] | [bigint], string],
    CalendarItem
  >,
  'createOpportunity' : ActorMethod<
    [string, string, bigint, bigint, string],
    Opportunity
  >,
  'createTodoItem' : ActorMethod<[string, string, string, [] | [bigint], string], TodoItem>,
  'deleteCalendarItem' : ActorMethod<[bigint], boolean>,
  'deleteComment' : ActorMethod<[bigint], boolean>,
  'deleteFileRecord' : ActorMethod<[bigint], boolean>,
  'deleteOpportunity' : ActorMethod<[bigint], boolean>,
  'deleteTodoItem' : ActorMethod<[bigint], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContact' : ActorMethod<[bigint], [] | [Contact]>,
  'getOpportunity' : ActorMethod<[bigint], [] | [Opportunity]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkContactToOpportunity' : ActorMethod<[bigint, bigint], boolean>,
  'listAllContacts' : ActorMethod<[], Array<Contact>>,
  'listAllUserProfiles' : ActorMethod<[], Array<UserProfileDTO>>,
  'listCalendarItems' : ActorMethod<[], Array<CalendarItem>>,
  'listComments' : ActorMethod<[bigint], Array<Comment>>,
  'listContactsByOpportunity' : ActorMethod<[bigint], Array<Contact>>,
  'listFileRecords' : ActorMethod<[bigint], Array<FileRecord>>,
  'listOpportunities' : ActorMethod<[], Array<Opportunity>>,
  'listTodoItems' : ActorMethod<[], Array<TodoItem>>,
  'makeAdmin' : ActorMethod<[Principal], undefined>,
  'assignConfidentialRole' : ActorMethod<[Principal], undefined>,
  'demoteToUser' : ActorMethod<[Principal], undefined>,
  'removeContact' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unlinkContactFromOpportunity' : ActorMethod<[bigint, bigint], boolean>,
  'updateContact' : ActorMethod<
    [bigint, string, string, string, string],
    [] | [Contact]
  >,
  'updateFileRecord' : ActorMethod<[bigint, string, string], [] | [FileRecord]>,
  'updateOpportunity' : ActorMethod<
    [bigint, string, string, bigint, bigint, string],
    [] | [Opportunity]
  >,
  'updateTodoItem' : ActorMethod<
    [bigint, string, string, string, [] | [bigint], string],
    [] | [TodoItem]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];